### ISSUE TITLE
Game crashes after entering

### ISSUE THREAD

**Issue by tupe12** [TheLimePixel/Crop-Block#13]
[crash-2018-04-17_15.57.26-server.txt](https://github.com/EmosewaPixel/Crop-Block/files/1919736/crash-2018-04-17_15.57.26-server.txt)

I think agricraft sprinklers dont work well when it rains

**Comment by tupe12** [comment]
and after trying to load again, I got this crash: 
[crash-2018-04-17_16.06.20-server.txt](https://github.com/EmosewaPixel/Crop-Block/files/1919764/crash-2018-04-17_16.06.20-server.txt)

**Comment by SilentAssassin01** [comment]
I'm getting the same crash. Looks like the sprinkler is consuming -4mb of water somehow? I've had the sprinklers running for a while though and while it's been raining. Only difference now is the reservoir feeding into the agricraft tanks now has a resonant servo on it rather than a basic one.

Initial crash:
[crash-2018-04-18_01.51.04-server.txt](https://github.com/EmosewaPixel/Crop-Block/files/1920125/crash-2018-04-18_01.51.04-server.txt)


Reloading crash:
[crash-2018-04-18_01.58.53-server.txt](https://github.com/EmosewaPixel/Crop-Block/files/1920126/crash-2018-04-18_01.58.53-server.txt)

**Comment by TheLimePixel** [comment]
Yeah, it randomly happens when raining.
