### ISSUE TITLE
Quartz Enriched Iron ingots impossible to create

### ISSUE THREAD

**Issue by babyonion** [TheLimePixel/Crop-Block#7]
Trying to trace recipes for Quartz Enriched Iron in JEI and there appears to be no way to create it, not through essence or thru the standard 3 iron + 1 quartz

**Comment by Ozzymud** [comment]
There is a crossbreed for quartz enriched iron seeds... nether quartz + iron

Edit: But the essence obtained crafts nothing... oops  

Edit2: the problem lies in the scripts, recipes.remove(<refinedstorage:quartz_enriched_iron>);
removes the essence recipe as well. Need to do an addShaped for the essence after removing the normal one.

Edit3: To add yourself until fixed, open up recipes.zs and add the following to the bottom:

```
// re-add quartz enriched iron via essence
recipes.addShaped(<refinedstorage:quartz_enriched_iron>*4,[
[<mysticalagriculture:quartz_enriched_iron_essence>,<mysticalagriculture:quartz_enriched_iron_essence>,<mysticalagriculture:quartz_enriched_iron_essence>],
[<mysticalagriculture:quartz_enriched_iron_essence>,null,<mysticalagriculture:quartz_enriched_iron_essence>],
[<mysticalagriculture:quartz_enriched_iron_essence>,<mysticalagriculture:quartz_enriched_iron_essence>,<mysticalagriculture:quartz_enriched_iron_essence>]
]);

```

**Comment by TheLimePixel** [comment]
Huh, that's the long way to do it.
